    version: '2'

    services:
      zeebe:
        image: camunda/zeebe:latest
        environment:
            - ZEEBE_LOG_LEVEL=debug
            - ZEEBE_HOST=0.0.0.0
        ports:
          - "51015:51015"
          - "51016:51016"
          - "51017:51017"
      monitor:
        image: camunda/zeebe-simple-monitor:latest
        ports:
          - "9090:8080"
        links:
          - zeebe